### ISSUE TITLE
1.20.1 or other 1.20 version support?

### ISSUE THREAD

**Issue by PinPanPaint** [eclipseisoffline/jukeboxcustomdiscfix#1]
Figured id ask, since a modpack I am using has a resource pack with custom discs, but this mod doesnt seem to be compatible. Would it be possible?

**Comment by eclipseisoffline** [comment]
Hi, a 1.20.1 version should be doable and reasonable since 1.20.1 seems to be a pretty big version for modding. I'll try to get on it, expect a release on Modrinth either later today or tomorrow.

**Comment by eclipseisoffline** [comment]
1.20.1 build published on Modrinth now, closing this issue
