### ISSUE TITLE
Forge/Neoforge port?

### ISSUE THREAD

**Issue by FensBK** [eclipseisoffline/jukeboxcustomdiscfix#2]
Do you have any plans to port the mod for the other mod loaders?

**Comment by eclipseisoffline** [comment]
Hi, I've been planning support for Neoforge for a while, but haven't had the time to get to it. I might have time to create a port later today or tomorrow.

**Comment by eclipseisoffline** [comment]
Neoforge support for 1.20.6, 1.20.5 and 1.20.4 is now available on Modrinth. Support for 1.20.1 will release later.

**Comment by Liink56** [comment]
I would like to know if the port to 1.20.1 forge is still in place?  I checked on modrinth and only the fabric version is available

I would love to have this mod, but I can't upgrade to another version

**Comment by eclipseisoffline** [comment]
Hi, I initially didn't create a Forge/Neoforge 1.20.1 port because the modloader for 1.20.1 doesn't directly support mixins. Shortly after publishing the Neoforge ports for 1.20.4/5/6 versions I got pretty busy in real life and college has started now too, which is why I haven't had time to create a 1.20.1 port. I'll try to see if I have time today/this weekend to publish one.

**Comment by eclipseisoffline** [comment]
A 1.20.1 Forge/Neoforge port should now be up on Modrinth. If you experience any issues while using it, please let me know. Thank you for your patience.

**Comment by Liink56** [comment]
thank you very much for your time ^^

**Comment by Liink56** [comment]
> A 1.20.1 Forge/Neoforge port should now be up on Modrinth. If you experience any issues while using it, please let me know. Thank you for your patience.

I came back from a stay with a friend and I took the opportunity to test the mod on my Aternos server and on a solo world, and the mod does not seem to work, there must be a bug, or you have to download a dependency that I forgot?

**Comment by eclipseisoffline** [comment]
Hi, could you please open a new issue with logs, server setup, version, etc.?

**Comment by Liink56** [comment]
ok, I'll see where to find it, but I really don't know how to use github very well.

**Comment by eclipseisoffline** [comment]
You can go [here](https://github.com/eclipseisoffline/jukeboxcustomdiscfix/issues/new?assignees=&labels=bug&projects=&title=%5BBUG%5D+) to create a new issue report. Make sure to create a proper title and description. The description should include your Minecraft setup (MC version, modloader + modloader version, version of this mod and other mods installed, etc.), and a log file with the mod installed (should be pretty easy to find on aternos, you can upload them to a site like [mclo.gs](https://mclo.gs) and include the link).
