### ISSUE TITLE
Client-side support

### ISSUE THREAD

**Issue by Jeremiah623** [eclipseisoffline/jukeboxcustomdiscfix#4]
Hi! I found this mod through a comment you left on the Mojang bug tracking website on a post relating to the issue of custom songs getting cut off when the vanilla songs end on discs.
You mentioned that client-side support for the mod might be added sometime later down the line, and I was wondering if there's an estimated time frame for when it will get added?

**Comment by eclipseisoffline** [comment]
Hi, as it says in the README, versions of this mod for 1.21 and above should have client side support:

> If you still wish to listen to custom discs through just the use of a resource pack though, you will need this mod. As of 1.21 this mod now fixes the bug client-side as well, meaning you can join every server with a custom disc resource pack, without the disc being cut off.

**Comment by Jeremiah623** [comment]
Oh awesome! Sounds good, ty!
