### ISSUE TITLE
[BUG] <Redstone signal cuts off at vanilla disc time>

### ISSUE THREAD

**Issue by MachCoyote** [eclipseisoffline/jukeboxcustomdiscfix#6]
**Describe the bug**
The redstone signal that a jukebox emits (and disappears when the disc stops playing) stops emitting at the time that the vanilla song would, rather than the song from the resource pack.

**To Reproduce**
1. Load a resource pack with a custom music disc.
2. Connect a redstone component to the jukebox.
3. Play the custom music disc.

**Expected behavior**
The redstone signal cuts off when the music finishes playing.

**Observed behavior**
The redstone signal cuts off midway through the music, at the time the original vanilla music would.

**Minecraft setup (please complete the following information):**
 - Minecraft version: [e.g. 1.21.1]
 - Fabric loader: [e.g. 0.16.7]
 - Jukebox Custom Disc Fix version: [e.g. 0.1.5-1.21.1]

**Comment by eclipseisoffline** [comment]
Hi, this is intended behaviour.

Every client connected to a server can have a different resource pack with a different song that has a different length. Therefore, it is impossible to know when to stop emitting a redstone signal.

As also mentioned in the README, if you are in control of the server you're playing on, or you play in singleplayer, it is preferred to make use of Minecraft's new [data driven jukebox songs](https://minecraft.wiki/w/Jukebox_song_definition) instead, which allow fine control over how a song is called, how long it is (and so, when the jukebox should stop emitting a redstone signal), and which signal a comparator outputs when measuring a jukebox with the disc in it. [Here's](https://misode.github.io/jukebox-song/) a useful generator for jukebox songs.
